import { useState } from 'react';
import AccessibleField from './examples/AccessibleField';
import MarkdownViewer from '../../components/MarkdownViewer';

const UseIdExamples = () => {
    const [showConcepts, setShowConcepts] = useState(false);

    return (
        <div className="container mx-auto p-4 max-w-4xl">
            <div className="bg-gradient-to-br from-blue-600 to-indigo-700 p-8 rounded-2xl shadow-2xl text-white">

                <div className="flex justify-between items-center mb-8">
                    <h2 className="text-3xl font-bold flex items-center gap-3">
                        <i className="fa-solid fa-fingerprint"></i> useId
                    </h2>
                    <button
                        onClick={() => setShowConcepts(!showConcepts)}
                        className="px-4 py-2 bg-white bg-opacity-20 hover:bg-opacity-30 backdrop-blur-sm text-white font-bold rounded-lg transition-all duration-200 shadow-lg border border-white border-opacity-30 text-sm"
                    >
                        {showConcepts ? '🙈 Hide Concepts' : '📖 Show Concepts'}
                    </button>
                </div>

                {showConcepts && (
                    <div className="mb-8 bg-white bg-opacity-95 backdrop-blur-lg rounded-xl p-6 border border-white border-opacity-20 shadow-2xl">
                        <div className="flex justify-between items-center mb-4">
                            <h4 className="text-xl font-bold flex items-center gap-2 text-gray-800">
                                <i className="fa-solid fa-book-open text-blue-600"></i>
                                useId Concepts
                            </h4>
                            <button
                                onClick={() => setShowConcepts(false)}
                                className="text-gray-500 hover:text-gray-700 transition-colors"
                            >
                                <i className="fa-solid fa-times"></i>
                            </button>
                        </div>
                        <MarkdownViewer filePath="/src/hooks/useId/UseIdConcepts.md" />
                    </div>
                )}

                <div className="bg-white text-gray-800 rounded-xl p-8">
                    <h3 className="text-2xl font-bold mb-6 flex items-center gap-2">
                        <i className="fa-solid fa-clipboard-list text-blue-600"></i>
                        Accessible Form
                    </h3>

                    <p className="mb-6 text-gray-600">
                        Each field below has a unique ID generated by <code className="bg-gray-100 px-2 py-1 rounded">useId()</code>.
                        This ensures proper label-input association for screen readers and accessibility tools.
                    </p>

                    <form>
                        <AccessibleField label="Full Name" />
                        <AccessibleField label="Email" type="email" />
                        <AccessibleField label="Password" type="password" />
                        <AccessibleField label="Confirm Password" type="password" />
                    </form>

                    <div className="mt-6 p-4 bg-blue-50 border-l-4 border-blue-500 rounded">
                        <p className="text-sm text-blue-800">
                            <i className="fa-solid fa-info-circle mr-2"></i>
                            <strong>Try it:</strong> Click on any label text. Notice how it focuses the corresponding input!
                            This works because <code>htmlFor</code> matches <code>id</code>.
                        </p>
                    </div>
                </div>

            </div>
        </div>
    );
};

export default UseIdExamples;
